import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

const version = readFileSync(new URL('../../src-tauri/Cargo.toml', import.meta.url), 'utf8').match(/^version = "([^"]+)"/m)![1]

test('fresh offline profile shows setup, preserves manual update feedback and becomes ready after saving', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.route('https://**', route => route.abort())
  await page.goto('/?onboarding')
  await expect(page.getByRole('heading', { name: 'Welcome to WoWthing Sync' })).toBeVisible()
  await expect(page.getByRole('list', { name: 'Setup steps' }).getByRole('listitem')).toHaveCount(2)
  await expect(page.getByText('Copy your API key from WoWthing Settings → Account.')).toBeVisible()
  await expect(page.getByText('Select the _retail_ folder that contains WTF/Account.')).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('first-launch.png'), animations: 'disabled' })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.screenshot({ path: test.info().outputPath('first-launch-dark.png'), animations: 'disabled' })
  await page.setViewportSize({ width: 440, height: 520 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('link', { name: 'Open Settings', exact: true })).toBeInViewport()
  await page.screenshot({ path: test.info().outputPath('first-launch-minimum.png'), animations: 'disabled' })
  await page.setViewportSize({ width: 520, height: 640 })
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  await page.getByRole('link', { name: 'Open Settings', exact: true }).click()
  await expect(page.getByText('Updates could not be checked. You can try again here.')).toBeVisible()
  await page.getByRole('button', { name: 'Check for Updates', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Could Not Check for Updates')
  await expect(page.getByText('Updates could not be checked right now. Try again later. Syncing can continue.')).toBeVisible()
  await expect(page.getByText('error sending request for url', { exact: false })).toBeHidden()
  await page.getByRole('alert').scrollIntoViewIfNeeded()
  await page.screenshot({ path: test.info().outputPath('manual-update-error.png'), animations: 'disabled' })
  await page.getByText('Technical details', { exact: true }).click()
  await expect(page.getByText('error sending request for url', { exact: false })).toBeVisible()
  await page.evaluate(() => { (window as unknown as { __SMOKE__: { updaterError: string | null } }).__SMOKE__.updaterError = null })
  await page.getByRole('button', { name: 'Check Again', exact: true }).click()
  await expect(page.getByText('You Are Up to Date', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'API Key', exact: true }).fill('smoke-fixture-key')
  await page.getByRole('button', { name: 'Save API Key', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Settings saved.' })).toBeVisible()
  await page.getByRole('link', { name: 'Status', exact: true }).click()
  await expect(page.getByText('API key saved securely.')).toBeVisible()
  await expect(page.locator('[aria-label=Complete]')).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'Welcome to WoWthing Sync' })).toBeVisible()
  await page.getByRole('link', { name: 'Open Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Choose Folder', exact: true }).click()
  await expect(page.locator('#folder-message[role=status]')).toHaveText('Settings saved.')
  await page.getByRole('link', { name: 'Status', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Not synced yet' })).toBeVisible()
  await expect(page.getByText('Watching 1 account for changes')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Sync Now', exact: true })).toBeEnabled()
  expect(errors).toEqual([])
})

test('built UI saves explicit drafts, keeps sync across navigation and reveals update state', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.route('https://**', route => route.abort()) // Hermetic: no external API, icon CDN or updater.
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Not synced yet' })).toBeVisible()
  await expect(page.getByText(`Version ${version}`)).toBeVisible()
  await expect(page.getByText('Watching 1 account for changes')).toBeVisible()
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await page.getByRole('textbox', { name: 'API Key', exact: true }).fill('smoke-fixture-key')
  const count = () => page.evaluate(() => (window as unknown as { __SMOKE__: { calls: { command: string }[] } }).__SMOKE__.calls.filter(call => call.command === 'save_api_key').length)
  expect(await count()).toBe(0)
  await page.getByRole('button', { name: 'Save API Key', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Settings saved.' })).toBeVisible()
  expect(await count()).toBe(1)
  await page.getByRole('textbox', { name: 'API Key', exact: true }).fill('invalid')
  await page.getByRole('button', { name: 'Save API Key', exact: true }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'API key is invalid' })).toBeVisible()
  const folders = () => page.evaluate(() => (window as unknown as { __SMOKE__: { calls: { command: string; args: { folder?: string } }[] } }).__SMOKE__.calls.filter(call => call.command === 'save_sync_folder').map(call => call.args.folder))
  await page.getByRole('button', { name: 'Choose Folder' }).click()
  await expect(page.locator('#folder-message[role=status]')).toHaveText('Settings saved.')
  expect(await folders()).toEqual(['/fixture/new_retail_'])
  await expect(page.getByText('This folder is "new_retail_", not "_retail_"')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('settings.png'), fullPage: true })
  await page.getByRole('button', { name: 'Check for Updates', exact: true }).click()
  await expect(page.getByText('You Are Up to Date', { exact: true })).toBeVisible()
  await expect(page.getByText('You Are Up to Date', { exact: true })).toBeHidden({ timeout: 6000 })
  await page.evaluate(() => {
    const fixture = (window as unknown as { __SMOKE__: { emit: (event: string, payload: unknown) => void; status: object } }).__SMOKE__
    fixture.emit('sync-status', { ...fixture.status, failures: [{ file: 'fixture.lua', message: 'HTTP 401' }] })
  })
  await expect(page.getByRole('alert').filter({ hasText: '1 account failed to upload.' })).toBeVisible()
  await page.getByRole('link', { name: 'View Accounts' }).click()
  await expect(page.getByRole('listitem').filter({ hasText: 'Failed · HTTP 401' })).toBeVisible()
  await expect(page.getByText('1 account needs attention')).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: 'Sync Now' }).click()
  await expect(page.getByRole('heading', { name: /^Synced / })).toBeVisible()
  await page.evaluate(() => {
    const fixture = (window as unknown as { __SMOKE__: { emit: (event: string, payload: unknown) => void; status: object } }).__SMOKE__
    fixture.emit('sync-status', { ...fixture.status, failures: [] })
  })
  await expect(page.getByRole('listitem').filter({ hasText: 'collector.lua' })).toContainText('ago')
  expect(errors).toEqual([])
  await page.screenshot({ path: process.env.SMOKE_SCREENSHOT ?? test.info().outputPath('dashboard.png') })
})
