name: 'Publish Release'
on:
  workflow_dispatch:
    inputs:
      vendor_version:
        type: string
        description: "Vendor Version (semver) for the release -- what will be visible."
        default: "0.0.1"
        required: true

jobs:
  create_release_tag:
    name: "Create release tag"
    env:
        VENDOR_VERSION: ${{ github.event.inputs.vendor_version || '0.0.1' }}

    runs-on: ubuntu-latest
    outputs:
        release_id: ${{ steps.create_release.outputs.id }}
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: |
              npm i -g npm@8.2.0
              npm ci
        - uses: softprops/action-gh-release@v1
          id: create_release
          name: Create release and add tauri-update.json
          with:
            tag_name: "v${{ env.VENDOR_VERSION }}"
            name: "v${{ env.VENDOR_VERSION }}"
            body: "v${{ env.VENDOR_VERSION }}"
            prerelease: true
            draft: false
            fail_on_unmatched_files: true

  publish-tauri:
    needs: create_release_tag
    env:
      RELEASE_ID: ${{ needs.create_release_tag.outputs.release_id }}
      VENDOR_VERSION: ${{ github.event.inputs.vendor_version || '0.0.1' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-12, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - run: git tag ${{ github.event.inputs.tag }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          releaseId: ${{ env.RELEASE_ID }}
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false