name: "Rust Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'apps/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Stub Nuxt dist output
        run: |
          mkdir -p dist
          test -f dist/index.html || echo '<!doctype html><title>stub</title>' > dist/index.html
        working-directory: apps/desktop

      - name: Cache Rust builds
        uses: swatinem/rust-cache@v2
        with:
          workspaces: 'apps/desktop/src-tauri -> target'

      - name: Run cargo test
        run: cargo test --manifest-path apps/desktop/src-tauri/Cargo.toml
