name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./landing
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm install
        working-directory: ${{ env.working-directory}}

      - run: NUXT_APP_BASE_URL=/wowthing-sync/ npx nuxt build --preset github_pages
        working-directory: ${{ env.working-directory}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.working-directory}}/.output/public

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
