name: UI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: apps/desktop/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: apps/desktop

      - name: Run unit tests
        run: npm run test:unit
        working-directory: apps/desktop
