name: 'Update the latest updater file'
on:
  workflow_dispatch:
    inputs:
      vendor_version:
        type: string
        description: "Vendor Version (semver) for the release -- what will be visible."
        default: "0.0.1"
        required: true

jobs:
  updater:
    # needs: publish-tauri
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VENDOR_VERSION: ${{ github.event.inputs.vendor_version || '0.0.1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git tag ${{ github.event.inputs.tag }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build tauri-update.json
        run: npm install && node generate-update-file.mjs
      - uses: softprops/action-gh-release@v1
        id: create_release
        name: Create release and add tauri-update.json
        with:
          tag_name: "v${{ env.VENDOR_VERSION }}"
          files: tauri-update.json
          fail_on_unmatched_files: true